server:
  port: 8080

spring:
  application:
    name: Expense-Tracker

  datasource:
    url: jdbc:mysql://localhost:3306/ex_tracker?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
        default_batch_fetch_size: 20
        enable_lazy_load_no_trans: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

general:
  cors_enabled: false
  default_locale: en

jwt:
  secret: dvd25vQuuiPZvi46advjewu
  token_validity_in_minutes: 480  # 8 * 60
  refresh_token_validity_in_minutes: 1440 # 24 * 60

otp:
  validity_duration_in_minutes: 2
